name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main  # Runs this workflow whenever changes are pushed to 'main'.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu virtual machine.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Fetches the latest code from GitHub.

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Use GitHub Secrets for security
        HOST: 54.211.241.172  # Replace with your EC2 public IP
        USER: ubuntu  # Default user for Ubuntu on AWS EC2.

      run: |
        # Store the SSH private key securely
        echo "$PRIVATE_KEY" > private_key.pem  
        chmod 600 private_key.pem  

        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          cd /var/www/html/  # Navigate to Apache web directory

          # Ensure the Git repository is set up properly
          if [ ! -d ".git" ]; then
            sudo rm -rf /var/www/html/*
            sudo git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY.git /var/www/html/
          else
            sudo git reset --hard  # Reset any local changes
            sudo git pull origin main  # Pull the latest changes from GitHub
          fi

          sudo
