name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging: Print if PRIVATE_KEY is empty
        run: |
          if [[ -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]]; then
            echo "ERROR: PRIVATE_KEY is empty!"
            exit 1
          else
            echo "✅ PRIVATE_KEY is set!"
          fi

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip "echo Connected successfully"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
            set -e  # Exit on error
            cd /var/www/html/

            # Ensure Git is installed
            which git || sudo apt-get install -y git

            # Add GitHub as a known host
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Pull latest changes
            sudo git pull https://github.com/YOUR_USERNAME/YOUR_REPO.git main

            # Fix ownership and restart Apache
            sudo chown -R www-data:www-data /var/www/html/
            sudo systemctl restart apache2
          EOF
