name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main  # Runs this workflow whenever changes are pushed to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu virtual machine.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Fetches the latest code from GitHub.

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmv3KN6fUm9WVjyRbixAKjcv8hnAT/0Lmmc496lxDv3GQSmBpaYQrSxapz4UEOetMJxz4aFl5WmSXhWbHx00Gd+YqPNoqTomHB6BrIq0xJCW+RhlmYwZoxrZQwWdjwUgXT6YvauJeGI9UmxsBZq/98+z4GAo7Z4WfyB5IjIM6Gz8rcDW+GhwW137C12HuauHUR4B96UYzT+XNxxOsZraGdLFpfEAMxyEjrhW5OM5epIjkaVpWEbFbPOGw3m4fjHkj+n+lckI/ctcaMMY5hXZZw2eahh0Inq5PylVKy3q/KMfkdtiuH+RYYTo85cVrVifZqyhBJEjWBq4FMYsU4TwKBNANy/pk/ufppYStUFB4Dq1QdH7dZC7coWvDUjOgm+iivMpicyX6BhEqna9sTVle7V55vgRSA5TF0EA8dzYaTtSFljOO+98Xrmly15/8EAK1eT0JT/7seuewwEUDvHEMb/bKSRQk+bUxdQM2lTGyY90d3TVsn5jWgXjAsnzyBtxlkBI/CEtxK4RrMqUWUbrwaSthpgJaoObE7q2QjO41AWaFB+HrPQxfKtsDab/wNTO2/LmCZHlF6hRFFRO2hJQT0OYXx3ejoHflrRkZVDWug5OzvlkjD6z/D+gkc16rlfQ2qHSQQDiV8jWr76fXRC27kBS6NnXl1UVanMi60Qwn+ZQ== ubuntu@ip-172-31-82-130
 }}  # Uses the SSH key stored in GitHub Secrets.
        HOST: ec2-54-211-241-172.compute-1.amazonaws.com # Replace with your EC2 instance's public IP.
        USER: ubuntu  # Default user for Ubuntu.

      run: |
        echo "$PRIVATE_KEY" > private_key.pem  # Creates a private key file.
        chmod 600 private_key.pem  # Sets proper permissions for the SSH key.
        
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          cd /var/www/html/  # Navigate to Apache web directory.
          sudo git pull origin main  # Pull the latest changes from GitHub.
          sudo chown -R www-data:www-data /var/www/html/  # Set correct permissions.
          sudo systemctl restart apache2  # Restart Apache server to apply changes.
        EOF
