name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging: Print if PRIVATE_KEY is empty
        run: |
          if [[ -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]]; then
            echo "ERROR: PRIVATE_KEY is empty!"
            exit 1
          else
            echo "✅ PRIVATE_KEY is set!"
          fi

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip "echo Connected successfully"


        # Deploy changes
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          cd /var/www/html/
          sudo git pull origin main
          sudo chown -R www-data:www-data /var/www/html/
          sudo systemctl restart apache2
        EOF
