name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 54.211.241.172  # Replace with your EC2 public IP
        USER: ubuntu

      run: |
        # Debugging: Print if PRIVATE_KEY is empty
        if [[ -z "$PRIVATE_KEY" ]]; then
          echo "ERROR: PRIVATE_KEY is empty!"
          exit 1
        fi

        # Save the private key
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Debugging: Check if the key works
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "echo Connected to EC2"

        # Deploy changes
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          cd /var/www/html/
          sudo git pull origin main
          sudo chown -R www-data:www-data /var/www/html/
          sudo systemctl restart apache2
        EOF
