name: Deploy to AWS Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}  # Store EC2 public IP as a GitHub Secret
        USER: ubuntu

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
        cd /var/www/html/
        git config --global credential.helper store
        git pull https://x-access-token:${{ secrets.GITHUB_DEPLOY_KEY }}@github.com/YOUR_USERNAME/YOUR_REPO.git main
        sudo chown -R www-data:www-data /var/www/html/
        sudo systemctl restart apache2
        EOF
        # Debugging: Check SSH Connection
        ssh -o StrictHostKeyChecking=no $USER@$HOST "echo Connected to EC2"

        # Deploy changes
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          set -e  # Exit on error
          cd /var/www/html/

          # Ensure Git is Installed
          which git || sudo apt-get install -y git

          # Pull latest changes
          sudo git pull origin main

          # Fix permissions and restart Apache
          sudo chown -R www-data:www-data /var/www/html/
          sudo systemctl restart apache2
        EOF
